### ISSUE TITLE
aikoyori.xyz: Typo

### ISSUE THREAD

**Issue by s1204IT** [Aikoyori/Aikoyori#3]
![Screenshot_20240425_151419_Chrome](https://github.com/Aikoyori/Aikoyori/assets/52069677/f52df5b7-c020-4e2c-974a-f2f5c45e2c8c)

I think this is not a "感じ", but a "**漢字**"!

If you want to convey the meaning of "if you think so", that "kanji"(感じ) is suitable.

**Comment by Aikoyori** [comment]
works as intended
